-- Leaderboard Entries

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_04_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_04_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_04_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_05_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_05_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_05_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_06_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_06_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_06_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_07_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_07_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_07_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_08_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_08_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_08_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_09_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_09_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_09_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_10_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_10_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_10_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_11_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_11_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_11_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2015_12_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_12_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2015_12_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_01_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_01_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_01_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_02_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_02_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_02_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_03_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_03_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_03_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_04_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_04_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_04_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_05_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_05_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_05_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_06_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_06_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_06_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_07_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_07_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_07_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_08_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_08_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_08_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_09_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_09_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_09_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_10_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_10_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_10_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_11_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_11_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_11_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2016_12_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_12_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2016_12_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2017_01_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2017_01_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2017_01_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2017_02_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2017_02_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2017_02_time;

DROP INDEX IF EXISTS idx_leaderboard_entries_2017_03_rank;
DROP INDEX IF EXISTS idx_leaderboard_entries_2017_03_score;
DROP INDEX IF EXISTS idx_leaderboard_entries_2017_03_time;

-- Power Ranking Entries

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_04_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_04_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_04_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_04_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_04_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_05_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_05_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_05_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_05_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_05_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_06_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_06_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_06_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_06_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_06_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_07_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_07_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_07_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_07_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_07_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_08_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_08_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_08_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_08_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_08_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_09_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_09_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_09_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_09_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_09_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_10_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_10_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_10_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_10_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_10_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_11_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_11_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_11_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_11_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_11_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2015_12_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_12_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_12_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_12_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2015_12_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_01_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_01_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_01_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_01_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_01_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_02_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_02_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_02_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_02_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_02_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_03_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_03_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_03_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_03_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_03_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_04_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_04_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_04_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_04_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_04_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_05_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_05_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_05_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_05_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_05_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_06_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_06_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_06_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_06_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_06_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_07_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_07_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_07_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_07_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_07_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_08_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_08_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_08_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_08_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_08_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_09_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_09_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_09_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_09_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_09_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_10_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_10_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_10_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_10_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_10_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_11_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_11_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_11_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_11_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_11_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2016_12_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_12_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_12_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_12_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2016_12_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2017_01_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_01_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_01_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_01_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_01_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2017_02_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_02_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_02_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_02_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_02_speed_rank_asc;

DROP INDEX IF EXISTS idx_power_ranking_entries_2017_03_deathless_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_03_rank_asc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_03_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_03_score_rank_desc;
DROP INDEX IF EXISTS idx_power_ranking_entries_2017_03_speed_rank_asc;

-- Daily Ranking Entries

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_04_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_04_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_05_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_05_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_06_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_06_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_07_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_07_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_08_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_08_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_09_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_09_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_10_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_10_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_11_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_11_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_12_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2015_12_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_01_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_01_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_02_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_02_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_03_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_03_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_04_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_04_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_05_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_05_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_06_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_06_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_07_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_07_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_08_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_08_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_09_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_09_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_10_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_10_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_11_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_11_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_12_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2016_12_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2017_01_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2017_01_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2017_02_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2017_02_rank_desc;

DROP INDEX IF EXISTS idx_daily_ranking_entries_2017_03_rank_asc;
DROP INDEX IF EXISTS idx_daily_ranking_entries_2017_03_rank_desc;