CREATE TABLE public.steam_user_pbs
(
  steam_user_pb_id serial NOT NULL,
  leaderboard_id smallint NOT NULL,
  steam_user_id integer NOT NULL,
  score integer,
  first_leaderboard_snapshot_id integer NOT NULL,
  first_rank integer NOT NULL,
  "time" double precision,
  win_count smallint,
  zone smallint,
  level smallint,
  is_win smallint,
  leaderboard_entry_details_id smallint NOT NULL,
  steam_replay_id integer,
  CONSTRAINT pk_steam_user_pbs_steam_user_pb_id PRIMARY KEY (steam_user_pb_id),
  CONSTRAINT fk_steam_user_pbs_first_leaderboard_snapshot_id FOREIGN KEY (first_leaderboard_snapshot_id)
      REFERENCES public.leaderboard_snapshots (leaderboard_snapshot_id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_steam_user_pbs_leaderboard_entry_details_id FOREIGN KEY (leaderboard_entry_details_id)
      REFERENCES public.leaderboard_entry_details (leaderboard_entry_details_id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_steam_user_pbs_leaderboard_id FOREIGN KEY (leaderboard_id)
      REFERENCES public.leaderboards (leaderboard_id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_steam_user_pbs_steam_user_id FOREIGN KEY (steam_user_id)
      REFERENCES public.steam_users (steam_user_id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_steam_user_pbs_steam_replay_id FOREIGN KEY (steam_replay_id)
      REFERENCES public.steam_replays (steam_replay_id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_steam_user_pbs UNIQUE (leaderboard_id, steam_user_id, score)
)
WITH (
    OIDS=FALSE
);

ALTER SEQUENCE steam_user_pbs_steam_user_pb_id_seq
RENAME TO steam_user_pbs_seq;

CREATE INDEX idx_steam_user_pbs_first_leaderboard_id
ON steam_user_pbs
USING btree
(leaderboard_id);

CREATE INDEX idx_steam_user_pbs_steam_user_id
ON steam_user_pbs
USING btree
(steam_user_id);

CREATE INDEX idx_steam_user_pbs_first_leaderboard_snapshot_id
ON steam_user_pbs
USING btree
(first_leaderboard_snapshot_id);

CREATE INDEX idx_steam_user_pbs_leaderboard_entry_details_id
ON steam_user_pbs
USING btree
(leaderboard_entry_details_id);

CREATE INDEX idx_steam_user_pbs_steam_replay_id
ON steam_user_pbs
USING btree
(steam_replay_id);

-- Rename old leaderboard entries and their constraints tables to backup versions

ALTER TABLE leaderboard_entries_2015_04 RENAME TO archived_leaderboard_entries_2015_04;
ALTER TABLE leaderboard_entries_2015_05 RENAME TO archived_leaderboard_entries_2015_05;
ALTER TABLE leaderboard_entries_2015_06 RENAME TO archived_leaderboard_entries_2015_06;
ALTER TABLE leaderboard_entries_2015_07 RENAME TO archived_leaderboard_entries_2015_07;
ALTER TABLE leaderboard_entries_2015_08 RENAME TO archived_leaderboard_entries_2015_08;
ALTER TABLE leaderboard_entries_2015_09 RENAME TO archived_leaderboard_entries_2015_09;
ALTER TABLE leaderboard_entries_2015_10 RENAME TO archived_leaderboard_entries_2015_10;
ALTER TABLE leaderboard_entries_2015_11 RENAME TO archived_leaderboard_entries_2015_11;

ALTER TABLE leaderboard_entries_2015_12 RENAME TO archived_leaderboard_entries_2015_12;
ALTER TABLE leaderboard_entries_2016_01 RENAME TO archived_leaderboard_entries_2016_01;
ALTER TABLE leaderboard_entries_2016_02 RENAME TO archived_leaderboard_entries_2016_02;
ALTER TABLE leaderboard_entries_2016_03 RENAME TO archived_leaderboard_entries_2016_03;
ALTER TABLE leaderboard_entries_2016_04 RENAME TO archived_leaderboard_entries_2016_04;
ALTER TABLE leaderboard_entries_2016_05 RENAME TO archived_leaderboard_entries_2016_05;
ALTER TABLE leaderboard_entries_2016_06 RENAME TO archived_leaderboard_entries_2016_06;
ALTER TABLE leaderboard_entries_2016_07 RENAME TO archived_leaderboard_entries_2016_07;
ALTER TABLE leaderboard_entries_2016_08 RENAME TO archived_leaderboard_entries_2016_08;
ALTER TABLE leaderboard_entries_2016_09 RENAME TO archived_leaderboard_entries_2016_09;
ALTER TABLE leaderboard_entries_2016_10 RENAME TO archived_leaderboard_entries_2016_10;
ALTER TABLE leaderboard_entries_2016_11 RENAME TO archived_leaderboard_entries_2016_11;
ALTER TABLE leaderboard_entries_2016_12 RENAME TO archived_leaderboard_entries_2016_12;
ALTER TABLE leaderboard_entries_2017_01 RENAME TO archived_leaderboard_entries_2017_01;
ALTER TABLE leaderboard_entries_2017_02 RENAME TO archived_leaderboard_entries_2017_02;
ALTER TABLE leaderboard_entries_2017_03 RENAME TO archived_leaderboard_entries_2017_03;

ALTER TABLE archived_leaderboard_entries_2015_04 
RENAME CONSTRAINT pk_leaderboard_entries_2015_04_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_04_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_04 
RENAME CONSTRAINT fk_leaderboard_entries_2015_04_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_04_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_05 
RENAME CONSTRAINT pk_leaderboard_entries_2015_05_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_05_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_05 
RENAME CONSTRAINT fk_leaderboard_entries_2015_05_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_05_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_06
RENAME CONSTRAINT pk_leaderboard_entries_2015_06_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_06_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_06
RENAME CONSTRAINT fk_leaderboard_entries_2015_06_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_06_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_07
RENAME CONSTRAINT pk_leaderboard_entries_2015_07_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_07_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_07 
RENAME CONSTRAINT fk_leaderboard_entries_2015_07_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_07_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_08
RENAME CONSTRAINT pk_leaderboard_entries_2015_08_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_08_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_08 
RENAME CONSTRAINT fk_leaderboard_entries_2015_08_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_08_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_09 
RENAME CONSTRAINT pk_leaderboard_entries_2015_09_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_09_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_09 
RENAME CONSTRAINT fk_leaderboard_entries_2015_09_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_09_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_10
RENAME CONSTRAINT pk_leaderboard_entries_2015_10_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_10_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_10 
RENAME CONSTRAINT fk_leaderboard_entries_2015_10_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_10_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_11
RENAME CONSTRAINT pk_leaderboard_entries_2015_11_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_11_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_11 
RENAME CONSTRAINT fk_leaderboard_entries_2015_11_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_11_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2015_12
RENAME CONSTRAINT pk_leaderboard_entries_2015_12_leaderboard_entry_id TO pk_archived_leaderboard_entries_2015_12_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2015_12 
RENAME CONSTRAINT fk_leaderboard_entries_2015_12_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2015_12_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_01
RENAME CONSTRAINT pk_leaderboard_entries_2016_01_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_01_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_01 
RENAME CONSTRAINT fk_leaderboard_entries_2016_01_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_01_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_02
RENAME CONSTRAINT pk_leaderboard_entries_2016_02_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_02_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_02 
RENAME CONSTRAINT fk_leaderboard_entries_2016_02_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_02_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_03
RENAME CONSTRAINT pk_leaderboard_entries_2016_03_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_03_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_03 
RENAME CONSTRAINT fk_leaderboard_entries_2016_03_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_03_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_04
RENAME CONSTRAINT pk_leaderboard_entries_2016_04_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_04_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_04 
RENAME CONSTRAINT fk_leaderboard_entries_2016_04_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_04_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_05
RENAME CONSTRAINT pk_leaderboard_entries_2016_05_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_05_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_05 
RENAME CONSTRAINT fk_leaderboard_entries_2016_05_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_05_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_06
RENAME CONSTRAINT pk_leaderboard_entries_2016_06_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_06_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_06
RENAME CONSTRAINT fk_leaderboard_entries_2016_06_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_06_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_07
RENAME CONSTRAINT pk_leaderboard_entries_2016_07_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_07_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_07 
RENAME CONSTRAINT fk_leaderboard_entries_2016_07_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_07_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_08
RENAME CONSTRAINT pk_leaderboard_entries_2016_08_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_08_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_08 
RENAME CONSTRAINT fk_leaderboard_entries_2016_08_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_08_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_09
RENAME CONSTRAINT pk_leaderboard_entries_2016_09_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_09_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_09 
RENAME CONSTRAINT fk_leaderboard_entries_2016_09_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_09_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_10
RENAME CONSTRAINT pk_leaderboard_entries_2016_10_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_10_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_10 
RENAME CONSTRAINT fk_leaderboard_entries_2016_10_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_10_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_11
RENAME CONSTRAINT pk_leaderboard_entries_2016_11_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_11_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_11 
RENAME CONSTRAINT fk_leaderboard_entries_2016_11_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_11_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2016_12
RENAME CONSTRAINT pk_leaderboard_entries_2016_12_leaderboard_entry_id TO pk_archived_leaderboard_entries_2016_12_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2016_12 
RENAME CONSTRAINT fk_leaderboard_entries_2016_12_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2016_12_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2017_01
RENAME CONSTRAINT pk_leaderboard_entries_2017_01_leaderboard_entry_id TO pk_archived_leaderboard_entries_2017_01_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2017_01 
RENAME CONSTRAINT fk_leaderboard_entries_2017_01_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2017_01_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2017_02
RENAME CONSTRAINT pk_leaderboard_entries_2017_02_leaderboard_entry_id TO pk_archived_leaderboard_entries_2017_02_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2017_02 
RENAME CONSTRAINT fk_leaderboard_entries_2017_02_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2017_02_leaderboard_snapshot_id;

ALTER TABLE archived_leaderboard_entries_2017_03
RENAME CONSTRAINT pk_leaderboard_entries_2017_03_leaderboard_entry_id TO pk_archived_leaderboard_entries_2017_03_leaderboard_entry_id;

ALTER TABLE archived_leaderboard_entries_2017_03 
RENAME CONSTRAINT fk_leaderboard_entries_2017_03_leaderboard_snapshot_id TO fk_archived_leaderboard_entries_2017_03_leaderboard_snapshot_id;